apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-bff-deployment
  labels:
    app: poc-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-bff
  template:
    metadata:
      labels:
        app: poc-bff
    spec:
      containers:
        - name: poc-bff
          image: poc/division
          imagePullPolicy: Never
          ports:
            - containerPort: 8090 # Port to expose in the container (must match below port)
          env:
            - name: SERVER_PORT
              value: "8090" # Default for Spring Boot is 8080, but you can change this if you want another
            - name: SERVICE_ENDPOINT
              value: "http://poc-backend-service:8090" # Must match BFF service name and port
            - name: APP_IS_BFF
              value: "true"