version: "3"

services:
    pocbackend:
        image: poc-image-backend
        restart: always
        container_name: pocbackend
        ports:
            - 8082:8082
        environment:
            - SERVER_PORT=8082
        networks:
            - pocNet  


    pocbff:
        image: poc-image-division
        depends_on:
            - pocbackend
        restart: always
        container_name: pocbff
        ports:
            - 8081:8081
        environment:
            - SERVER_PORT=8081
            - SERVICE_ENDPOINT=http://pocbackend:8082
            - APP_IS_BFF=true
        networks:
            - pocNet   


    pocdivision:
        image: poc-image-division
        depends_on:
            - pocbff        
        restart: always
        container_name: pocdivision
        ports:
            - 8080:8080
        environment:
            - SERVER_PORT=8080
            - SERVICE_ENDPOINT=http://pocbff:8081
            - APP_IS_BFF=false
        networks:
            - pocNet  


# Definition of network
networks:
    pocNet:
        driver: bridge              
